# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0010_contest_similarity_check_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('problem', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('public_time', models.DateTimeField()),
                ('is_solved', models.BooleanField(default=False)),
                ('ans_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_auth', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('que_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='que_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_question',
                'ordering': ('-public_time',),
            },
        ),
    ]
